development:
  adapter: postgresql
  encoding: utf8
  database: cards_development
  username:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: cards_test
  username:
  host: localhost

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: cards
  pool: 5
  username: user
  password: ks86ybdl!
